apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visits-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - visits.local
      secretName: visits-tls
  rules:
    - host: visits.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visits-app
                port:
                  number: 80
